### ISSUE TITLE
Char group download not working on bridges

### ISSUE THREAD

**Issue by mdlincoln** [cmu-lib/printprob-db#14]
- [x] Need to tell `requests` where the CA certs are on Bridges, and the files in `/etc/ssl/cert` don't seem to be cutting it so far
- [x] Even if I skip verification, the zipfile produced by bridges is corrupt (although it works fine locally and on the library test server). Wonder if it's a problem with write access to the temporary python folder.

**Comment by mdlincoln** [comment]
Part 2 addressed by using tarfiles and setting up a writable temp directory

**Comment by mdlincoln** [comment]
For pt. 1 i've put in a query to PSC staff about where they keep their ca certificates

**Comment by chrisvvarren** [comment]
@mdlincoln guessing you never heard back from PSC re: certificates - shall i ping again?

**Comment by mdlincoln** [comment]
Looks like the certificate issue has been resolved, but filenames aren't being set properly for the individual character files inside the zip that gets downloaded, so you can't usefully access them. Looking into some adjustments today.

**Comment by mdlincoln** [comment]
@chrisvvarren try it out again. It's still a touch slow for large character groups, but the labels seem to be working now.

**Comment by chrisvvarren** [comment]
awesome, thank you!
