### ISSUE TITLE
Display underlying page image for character in context

### ISSUE THREAD

**Issue by chrisvvarren** [cmu-lib/printprob-db#26]

**Comment by mdlincoln** [comment]
IIIF server outputs the image info JSON at the correct path 

<https://printprobdb.psc.edu/iiif//books/clark/anon_xxxxx_yyyyy_00height_kingscabinet/lines_color/anon_xxxxx_yyyyy_00height_kingscabinet-0061_page1r.tif/info.json>

However the generated JSON inherits the path of the host vm013, providing the image id

`http://vm013.bridges2.psc.edu:8080/books/clark/anon_xxxxx_yyyyy_00height_kingscabinet/lines_color/anon_xxxxx_yyyyy_00height_kingscabinet-0061_page1r.tif`

Either need to find a way to adjust the nginx reverse proxy to rewrite that `@id` path, or find a way to change the configuration of the iiif server so it rewrites itself.
