### ISSUE TITLE
Modify Image Size for Viewing and Reviewing Characters

### ISSUE THREAD

**Issue by chrisvvarren** [cmu-lib/printprob-db#28]
small dimensions of some images make them hard to see.  possible to modify image sizes for smaller stuff like 
[these](https://printprobdb.psc.edu/character_review?book=7ccdb6bc-b83c-470e-99a1-210c2309e36d&character_class=E_uc)

**Comment by mdlincoln** [comment]
Pushed out a small update to try out some resizing options - we can try out at the meeting today
